load("//packages/asciidoctor_compiler:defs.bzl", "asciidoctor_njk_templates")

asciidoctor_njk_templates(
    name = "asciidoctor",
    section = "section.njk",
    visibility = ["//visibility:public"],
)
